#!/usr/bin/env bash

# test directories layout
#
# test - this directory, contains test scripts
# test/testrepo - borg repo created for testing
# test/testfiles - generated file tree to use for test backup
# test/borg_base_dir - BORG_BASE_DIR, borg cached and metadata for the test



errcode=0

# save command line option, just in case there is one
option="$1"

# the version that should be reported by the tools
TEST_VER="0.3"

# make sure we are operating from the test directory
TEST_DIR="$(dirname $(realpath "$0"))"
cd "${TEST_DIR}"

# set up directories used in testing
# borg itself recognizes BORG_BASE_DIR as the place to store its caches
export BORG_BASE_DIR=$(pwd)/borg_base_dir
TEST_REPO=$(pwd)/testrepo
TEST_FILES=$(pwd)/testfiles

test_start()
{
    local title
    title="$1"
    printf "TEST: %-50s ... " "${title}"
}

# compare actual to expected results strings
# $1 - actual
# $2 - expected
# set global errcode if error occurs
test_result_matches()
{
    local expected actual
    actual="$1"
    expected="$2"
    if [ "${actual}" = "${expected}" ]
    then
        printf "OK\n"
    else
        printf "ERROR\n"
        printf "  vvvvvvvvvvvvvvvv\n"
        printf "  expected=\n[${expected}]\n"
        printf "  actual=\n[${actual}]\n"
        printf "  ^^^^^^^^^^^^^^^^\n"
        errcode=1
    fi
}

# checks if result strings contain another string
# $1 - actual string
# $2 - contains string
# set global errcode if error occurs
test_result_contains()
{
    local contains actual
    actual="$1"
    contains="$2"
    echo "${actual}" | grep -q "${contains}"
    ret=$?
    if [ ${ret} -eq 0 ]
    then
        printf "OK\n"
    else
        printf "ERROR\n"
        printf "  vvvvvvvvvvvvvvvv\n"
        printf "  search_for=\n[${contains}]\n"
        printf "  actual=\n[${actual}]\n"
        printf "  ^^^^^^^^^^^^^^^^\n"
        errcode=1
    fi
}

# check if a return code is true
# $1 - the return code
# $2 - error message
test_true()
{
    local result msg
    result=$1
    msg="$2"
    if [ ${result} -eq 0 ]
    then
        printf "OK\n"
    else
        printf "ERROR\n"
        printf "  vvvvvvvvvvvvvvvv\n"
        printf "  ${msg}\n"
        printf "  ^^^^^^^^^^^^^^^^\n"
        errcode=1
    fi
}

# check if a return code is false
# $1 - the return code
# $2 - error message
test_false()
{
    local result msg
    result=$1
    msg="$2"
    if [ ${result} -ne 0 ]
    then
        printf "OK\n"
    else
        printf "ERROR\n"
        printf "  vvvvvvvvvvvvvvvv\n"
        printf "  ${msg}\n"
        printf "  ^^^^^^^^^^^^^^^^\n"
        errcode=1
    fi
}

# clean artifacts generated by the test
clean()
{
    rm -rf ${BORG_BASE_DIR}
    rm -rf ${TEST_REPO}
    rm -rf ${TEST_FILES}
    rm -rf ${TEST_DIR}/testconfig
    rm -rf ${TEST_DIR}/xdgconfig
    rm -f "${TEST_DIR}/bs-repo.cfg"
    rm -f "${TEST_DIR}/bs-set-test.cfg"
    rm -f "${TEST_DIR}/bs-exclude-common.cfg"
}

# provide an option to just clean up any test residue but dont run the test
# this can be used to clean up a work tree
if [ "${option}" = "-c" ]
then
    echo "Cleaning test residue only"
    clean
    exit 0
fi

echo "------------------------"
echo "Starting BS-SCRIPTS test"
echo "------------------------"

########################################
#
# SETUP FOR TESTS
#
########################################

# make sure we are operating from the test directory
TEST_DIR="$(dirname $(realpath "$0"))"
cd "${TEST_DIR}"

# set up directories used in testing
# borg itself recognizes BORG_BASE_DIR as the place to store its caches
export BORG_BASE_DIR=$(pwd)/borg_base_dir
TEST_REPO=$(pwd)/testrepo
TEST_FILES=$(pwd)/testfiles

# clean up any prior residue
echo "Cleaning prior test data"
clean

# create the test file tree
mkdir ${TEST_FILES}
cd ${TEST_FILES}

# create several folder, each containing several files, of random data
echo "Creating test file tree"
for d in {0..4}
do
    mkdir "folder_${d}"
    cd "folder_${d}"
    for f in {0..8}
    do
        head -c 1024 < /dev/urandom > "file_${f}.bin"
    done
    cd ..
done
cd ..

# BORG_REPO may be set for real world use on the development machine, and
# we dont want to use that repo for testing. So unset it so that the test
# configs will be used
unset BORG_REPO

# initialize the test repo
# use no encryption to avoid needing to mess with passwords
echo "Creating borg test repo"
borg init --encryption none ${TEST_REPO}

########################################
#
# BS-BACKUP BASIC/VERSION TEST
#
# Invoke -V and make sure script runs and returns expected version
#
########################################
test_start "bs-backup basic version test"
expected="bs-backup from bs-scripts package ${TEST_VER}
https://github.com/kroesche/bs-scripts"
actual=$(../bs-backup -V)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  check correct output"
test_result_matches "${actual}" "${expected}"

########################################
#
# BS-LOGS BASIC/VERSION TEST
#
# Invoke -V and make sure script runs and returns expected version
#
########################################
test_start "bs-logs basic version test"
expected="bs-logs from bs-scripts package ${TEST_VER}
https://github.com/kroesche/bs-scripts"
actual=$(../bs-logs -V)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  check correct output"
test_result_matches "${actual}" "${expected}"

########################################
#
# CONFIG FROM SCRIPTS DIR
#
# Try -l, verify scripts dir is used
#
########################################

# BS-BACKUP

test_start "bs-backup check config location, scripts dir"
actual=$(../bs-backup -l -v)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  verify scripts dir config"
contains="Using scripts dir"
test_result_contains "${actual}" "${contains}"
test_start "  verify scripts path"
contains="$(realpath $(pwd)/..)/bs-repo.cfg"
test_result_contains "${actual}" "${contains}"

# BS-LOGS

test_start "bs-logs check config location, scripts dir"
actual=$(../bs-logs -l -v)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  verify scripts dir config"
contains="Using scripts dir"
test_result_contains "${actual}" "${contains}"
test_start "  verify scripts path"
contains="$(realpath $(pwd)/..)/bs-repo.cfg"
test_result_contains "${actual}" "${contains}"

########################################
#
# RUN BACKUP WITHOUT PROPER CONFIG
#
# Try -b, should fail due to missing config
# This falls back to scripts dir for config, but BORG_REPO
# is not defined there so that is why there is an error
#
########################################
test_start "bs-backup with missing config"
actual="$(../bs-backup -b example 2>&1)"
ret=$?
test_false ${ret} "expected error return"
test_start "  verify expected errors"
contains="borg create: error: argument ARCHIVE: Invalid location format"
test_result_contains "${actual}" "${contains}"

########################################
#
# CHECK BS_SCRIPTS_CONFIG USER DEFINED CONFIG DIR
#
# create repo cfg and test set in a separate config dir
# - verify config location being used
# - -l switch show correct list
#
########################################
mkdir testconfig
echo "Generating configuration file in config dir"
# only need BORG_REPO and not any credentials since
# encryption is not used for the test repo
cat << REPO_CFG > testconfig/bs-repo.cfg
BORG_REPO="${TEST_REPO}"
REPO_CFG

echo "Generating test set configuration in test dir"
cat << REPO_CFG > testconfig/bs-set-test.cfg
BACKUP_SET_DESCRIPTION="Test custom backup set"
BACKUP_CUSTOM_FLAGS="--exclude 'foo/bar baz'"
BACKUP_SOURCE_PATHS="$(pwd)/testfiles"
REPO_CFG

test_start "bs-backup user config location"
actual=$(BS_SCRIPTS_CONFIG="$(pwd)/testconfig" ../bs-backup -l -v)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  verify custom config dir"
contains="Using user defined BS_SCRIPTS_CONFIG as config location"
test_result_contains "${actual}" "${contains}"
test_start "  verify scripts path"
contains="$(realpath $(pwd)/testconfig)/bs-repo.cfg"
test_result_contains "${actual}" "${contains}"

test_start "list test sets in user config location"
actual=$(BS_SCRIPTS_CONFIG="$(pwd)/testconfig" ../bs-backup -l)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  verify list items"
expected='
Available backup configurations
-------------------------------
test             Test custom backup set'
test_result_matches "${actual}" "${expected}"

########################################
#
# CHECK XDG_CONFIG_HOME DEFINED CONFIG DIR
#
# create repo cfg and test set in a separate config dir
# - verify config location being used
# - -l switch show correct list
#
########################################
mkdir -p xdgconfig/bs-scripts
echo "Generating configuration file in XDG config dir"
# only need BORG_REPO and not any credentials since
# encryption is not used for the test repo
cat << REPO_CFG > xdgconfig/bs-scripts/bs-repo.cfg
BORG_REPO="${TEST_REPO}"
REPO_CFG

echo "Generating test set configuration in xdg test dir"
cat << REPO_CFG > xdgconfig/bs-scripts/bs-set-test.cfg
BACKUP_SET_DESCRIPTION="Test xdg custom backup set"
BACKUP_CUSTOM_FLAGS="--exclude 'foo/bar baz'"
BACKUP_SOURCE_PATHS="$(pwd)/testfiles"
REPO_CFG

test_start "bs-backup xdg config location"
actual=$(XDG_CONFIG_HOME="$(pwd)/xdgconfig" ../bs-backup -l -v)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  verify xdg config dir"
contains="Using XDG_CONFIG_HOME for configuration"
test_result_contains "${actual}" "${contains}"
test_start "  verify scripts path"
contains="$(realpath $(pwd)/xdgconfig)/bs-scripts/bs-repo.cfg"
test_result_contains "${actual}" "${contains}"

test_start "list test sets in xdg config location"
actual=$(XDG_CONFIG_HOME="$(pwd)/xdgconfig" ../bs-backup -l)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  verify list items"
expected='
Available backup configurations
-------------------------------
test             Test xdg custom backup set'
test_result_matches "${actual}" "${expected}"

########################################
#
# CHECK LOCAL CONFIG
#
# create repo cfg and test set in local dir
# - verify config location being used
# - -l switch show correct list
#
########################################
echo "Generating configuration file in local dir"
# only need BORG_REPO and not any credentials since
# encryption is not used for the test repo
cat << REPO_CFG > bs-repo.cfg
BORG_REPO=${TEST_REPO}
REPO_CFG

echo "Generating common exclude file in local dir"
cat << REPO_CFG > bs-exclude-common.cfg
*/.DS_*
REPO_CFG

echo "Generating test set configuration in local dir"
cat << REPO_CFG > bs-set-test.cfg
BACKUP_SET_DESCRIPTION="Test backup set"
BACKUP_CUSTOM_FLAGS="--exclude 'foo/bar baz'"
BACKUP_SOURCE_PATHS="$(pwd)/testfiles"
REPO_CFG

test_start "bs-backup local config location"
actual=$(../bs-backup -l -v)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  verify local config dir"
contains="Using current directory for configuration"
test_result_contains "${actual}" "${contains}"
test_start "  verify scripts path"
contains="$(realpath $(pwd))/bs-repo.cfg"
test_result_contains "${actual}" "${contains}"

test_start "list test sets in local config location"
actual=$(../bs-backup -l)
ret=$?
test_true ${ret} "unexpected error code: ${ret}"
test_start "  verify list items"
expected='
Available backup configurations
-------------------------------
test             Test backup set'
test_result_matches "${actual}" "${expected}"

########################################
#
# RUN A BACKUP OF THE TEST DATA
#
# - complete with no error
# - expected rc=0 in log
# - check for key output lines in the log
#
########################################
test_start "run a backup"
actual="$(../bs-backup -b test 2>&1)"
ret=$?
test_true ${ret} "${actual}"
test_start "  expected return codes in log"
rc0cnt=$(echo "${actual}" | grep "terminating with success status, rc 0"|wc -l|xargs echo)
test ${rc0cnt} -eq 2
ret=$?
test_true ${ret} "expected 2 rc 0 lines, found: ${rc0cnt}"

################################################################################
#
# END OF SCRIPT
# PROCESS RESULT
#
################################################################################
echo ""
echo "----------------------------"
if [ ${errcode} -ne 0 ]
then
    echo "Test finished with errors"
else
    echo "Test finished with no errors"
fi
echo "----------------------------"
exit ${errcode}






exit 0





test_message "bs-backup -b, run a backup"
actual="$(../bs-backup -b test 2>&1)"
lasterr=$?
if [ ${lasterr} -eq 0 ] # check for direct error code return
then
    echo "OK"
else
    echo "ERROR"
    printf "  vvvvvvvvvvvvvvvv\n"
    echo   "  error code returned from operation: ${lasterr}"
    printf "  ^^^^^^^^^^^^^^^^\n"
    errcode=1
fi

# now examine results for expected contents

test_message "backup success result"
rc0cnt=$(echo "${actual}" | grep "terminating with success status, rc 0"|wc -l)
if [ ${rc0cnt} -eq 2 ]
then
    echo "OK"
else
    echo "ERROR"
    printf "  vvvvvvvvvvvvvvvv\n"
    echo   "  Did not find expected number of rc 0"
    printf "  ^^^^^^^^^^^^^^^^\n"
    errcode=1
fi

expected='+++BACKUP: test
\-\-\-BACKUP
+++PRUNE
\-\-\-PRUNE
+++COMPACTING
\-\-\-COMPACTING
Backup, Prune, and Compact finished successfully'

all_matches_ok=1
test_message "backup log output"
while read -r line
do
    echo "${actual}" | grep -q "${line}"
    matches=$?
    if [ ${matches} -ne 0 ]
    then
        echo "ERROR"
        printf "  vvvvvvvvvvvvvvvv\n"
        echo   "  Missing some expected output:"
        echo   "  [${line}]"
        printf "  ^^^^^^^^^^^^^^^^\n"
        all_matches_ok=0
        break
    fi
done < <(echo "${expected}")

if [ ${all_matches_ok} -eq 1 ]
then
    echo "OK"
else
    errcode=1
fi


if [ ${errcode} -eq 0 ]
then
    printf "\nTEST PASSES\n"
else
    printf "\nTEST FAILED\n"
fi
exit ${errcode}

